# Generated by Django 5.1.3 on 2025-02-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ducmentsno', models.CharField(max_length=255, null=True)),
                ('Acidno', models.CharField(max_length=255, null=True)),
                ('NoCR', models.CharField(max_length=255, null=True)),
                ('documents_received_date', models.CharField(max_length=255)),
                ('expected_arrival_date', models.CharField(max_length=255)),
                ('storge_data', models.CharField(default='not storge', max_length=255)),
                ('Delivery_data', models.CharField(default='not arrival', max_length=255)),
                ('NoCE_data', models.CharField(max_length=255, null=True)),
                ('End_customs_data', models.CharField(max_length=255, null=True)),
                ('exchange_data', models.CharField(max_length=255, null=True)),
                ('vessel_name', models.CharField(max_length=255)),
                ('bill_of_lading', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('packages_count', models.IntegerField()),
                ('invoice_number', models.CharField(max_length=255)),
                ('comment', models.TextField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marine.company')),
            ],
        ),
    ]
