# Generated by Django 5.1.3 on 2025-02-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='agency',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
