# Generated by Django 5.1.3 on 2025-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0002_shipment_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
