# Generated by Django 5.1.3 on 2025-02-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0003_alter_shipment_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='packages_count',
            field=models.CharField(max_length=255),
        ),
    ]
