# Generated by Django 5.1.3 on 2025-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0004_alter_shipment_packages_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='storge_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
