# Generated by Django 5.1.3 on 2025-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0005_alter_shipment_storge_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='Delivery_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
