# Generated by Django 4.2 on 2025-02-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0007_alter_shipment_acidno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='Acidno',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='NoCR',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
