# Generated by Django 4.2 on 2025-04-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0009_alter_shipment_acidno_alter_shipment_nocr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر')], max_length=3)),
                ('currency', models.CharField(choices=[('EGP', 'جنيه'), ('USD', 'دولار'), ('EUR', 'يورو')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
